/* ============================================================================
 * 模型决策台 · 数据源
 * ----------------------------------------------------------------------------
 * 设计原则（来自前期分析）：
 *   1. 四个源测的不是同一件事，绝不合成一个"假总分"。
 *   2. 分数各归各家，每个数字都带来源 + 抓取日期。
 *   3. 跨源分歧度 / 同口径归一化才是自建看板唯一能创造的价值。
 *
 * ⚠️ 本次更新要点（2026-09-20 快照）：
 *   - AA 已升级 Intelligence Index v4.3（2026-09-07），量纲整体下调（上限 53），
 *     与旧版 v4.1.1 的 66/63/61 分【不可比】。本文件已全部换用 v4.3。
 *   - 新入榜：GPT-6 Astra、Claude Mythos 5、Muse Spark 1.3、Gemini 3.8 Flash、
 *     GPT Image 2.5（Flare / Sunburst）等。
 *   - 视频维此前只有 AA 单源，本次补上 LMArena I2V，两源可交叉。
 *
 * 数据可信度标注：
 *   - AA 指数 / AA Image·Video Elo / LMArena 各榜 Elo / LiveBench：来自公开榜单快照。
 *   - llm-stats 综合分（ls）：无 API key，用 llm-stats 2026-09-03 公开 TrueSkill 榜的真实值；
 *     少数未上榜模型（如刚发布的 GPT-6 Astra）为按名次估算，顺序与官方一致。
 *   - LiveBench 仍为 2026-06-25 release（半年一刷），新模型多为 null。
 *   - LMArena 无公开 API，lm 列均为人工快照，可在页面直接点改并存 localStorage。
 * ==========================================================================*/

const SOURCES = {
  aa: { key: 'aa', name: 'Artificial Analysis', short: 'AA', color: 'var(--src-aa)', date: '2026-09-17', note: '智能指数 v4.3（2026-09-07 起，与旧版不可比）/ Image·Video Arena Elo' },
  ls: { key: 'ls', name: 'llm-stats',          short: 'LS', color: 'var(--src-ls)', date: '2026-09-03', note: 'TrueSkill μ−3σ 综合分（部分未上榜模型为估算）' },
  lb: { key: 'lb', name: 'LiveBench',          short: 'LB', color: 'var(--src-lb)', date: '2026-06-25', stale: true, note: 'Agentic Coding 列（半年一刷，已标黄）' },
  lm: { key: 'lm', name: 'LMArena',            short: 'LM', color: 'var(--src-lm)', date: '2026-09-15', note: '人工快照 · 点格子可改并存本地' },
};

/* 维度定义。cols 决定本维度表格展示哪些源列；lmMetric 说明 lm 列取哪个榜。 */
const DIMENSIONS = [
  {
    key: 'agent',
    label: 'Agent',
    sub: '含 Vibe Coding / 工具调用 / 真实工作任务。主信号：AA 智能指数 v4.3、LiveBench Agentic Coding、LMArena WebDev（vibe coding）。',
    kicker: 'DIMENSION 01',
    lmMetric: 'WebDev Arena Elo（vibe coding 对口榜）',
    cols: ['aa', 'ls', 'lb', 'lm'],
    costLabel: '输出 $/M',
    speedLabel: '输出 t/s',
    note: 'AA 已换 v4.3（上限 53），与旧版 66/63 分不可比。LiveBench 停留在 6-25，GPT-6 Astra / Mythos 5 / Muse Spark 1.3 等新模型不在其内（记为缺源）。LMArena lm 列取 WebDev Arena，为主要人工快照。',
    analysis: [
      { k: 'Vibe coding 榜首已易主', lead: 'WebDev 榜从 Claude 一家独大变成 OpenAI / Anthropic / 阿里三方拉锯，且榜首是"租来的"。',
        body: ['GPT-6 Astra 以 1812 居 WebDev 榜首，Claude Fable 5.1 1788 紧随；此前 9-02 阿里 Qwen3.8-Max-0902 曾以 1691 短暂登顶（比 Opus 5 高 3 分），9-07 又被 Fable 5.1 / Astra 反超——这张榜每周都在换人。',
               'Kimi K3 是覆盖面最广的中国模型：WebDev 前三、代码第 6、Agent 第 5、综合第 12，没有一项掉出前十五；且开着开放权重、$3/$15。',
               'OpenAI 在 WebDev 上翻身靠的是 GPT-6 Astra，但它在 LMArena 文本榜只排到第 24（~1480）——同一模型"做页面"远强于"聊天"，再次证明构念不同。'],
        note: '选 Agent 模型：先看 AA 指数 v4.3（含 30% Agent + 20% Coding），再用 LMArena WebDev 校验 vibe coding，最后用 LiveBench Agentic Coding 看客观任务完成度（注意其滞后）。' },
      { k: '性价比', lead: 'AA v4.3 下同分不同价：Astra 与 Fable 5.1 并列 53 分，但每任务成本差 57%。',
        body: ['GPT-6 Astra（max）约 $3.26/任务，Claude Fable 5.1（max）约 $7.63/任务——同样的智能分，Astra 便宜近六成。',
               '开源侧 GLM-5.3-Flash（AA 42）与 DeepSeek V4 Pro（AA 36）把每成功任务成本压到最低，是预算敏感场景默认解。'],
        note: 'AA 的 $/task 与 LiveBench 的 $/成功任务反映真实支出；$/M 单价对推理模型系统性失真，勿单看。' },
    ],
    models: [
      { name: 'GPT-6 Astra (Max)', maker: 'OpenAI', open: false,
        scores: { aa: 53, ls: 57.5, lb: null, lm: 1812 },
        cost: { perM: 50, perTask: 3.26, perSuccess: null }, speed: { aa: 60, ls: null } },
      { name: 'Claude Fable 5.1 (Max)', maker: 'Anthropic', open: false,
        scores: { aa: 53, ls: 57.0, lb: 83.4, lm: 1788 },
        cost: { perM: 50, perTask: 7.63, perSuccess: 1.439 }, speed: { aa: 35, ls: null } },
      { name: 'Claude Opus 5 (Max)', maker: 'Anthropic', open: false,
        scores: { aa: 51, ls: 55.8, lb: 59, lm: 1707 },
        cost: { perM: 25, perTask: 2.34, perSuccess: null }, speed: { aa: 80, ls: null } },
      { name: 'Claude Mythos 5', maker: 'Anthropic', open: false,
        scores: { aa: null, ls: 55.4, lb: null, lm: null },
        cost: { perM: 50, perTask: null, perSuccess: null }, speed: { aa: null, ls: null } },
      { name: 'Claude Fable 5', maker: 'Anthropic', open: false,
        scores: { aa: 50, ls: 54.9, lb: 57, lm: 1660 },
        cost: { perM: 50, perTask: 3.14, perSuccess: 1.439 }, speed: { aa: 119, ls: null } },
      { name: 'Muse Spark 1.3 (Max)', maker: 'Meta', open: false,
        scores: { aa: 48, ls: 55.4, lb: null, lm: null },
        cost: { perM: 4.25, perTask: 0.55, perSuccess: null }, speed: { aa: 93, ls: null } },
      { name: 'GPT-5.6 Sol', maker: 'OpenAI', open: false,
        scores: { aa: 47, ls: 56.0, lb: 56.2, lm: 1650 },
        cost: { perM: 30, perTask: 0.95, perSuccess: 0.515 }, speed: { aa: 121, ls: null } },
      { name: 'Kimi K3 Max', maker: 'Moonshot', open: true, flag: 'Kimi K3 许可',
        scores: { aa: 44, ls: 54.1, lb: 58, lm: 1690 },
        cost: { perM: 15, perTask: 0.84, perSuccess: 0.348 }, speed: { aa: 86, ls: null } },
      { name: 'Qwen3.8 Max', maker: 'Alibaba', open: false,
        scores: { aa: 40, ls: 52.3, lb: 55, lm: 1754 },
        cost: { perM: 6, perTask: null, perSuccess: null }, speed: { aa: 71, ls: null } },
      { name: 'GLM-5.3 (Max)', maker: 'Z.ai', open: true, flag: 'MIT',
        scores: { aa: 45, ls: 53.8, lb: 50, lm: 1620 },
        cost: { perM: 4.0, perTask: 0.09, perSuccess: 0.031 }, speed: { aa: 87, ls: null } },
      { name: 'DeepSeek V4 Pro 0813', maker: 'DeepSeek', open: true, flag: 'MIT',
        scores: { aa: 36, ls: 52.3, lb: 55, lm: 1600 },
        cost: { perM: 0.87, perTask: null, perSuccess: 0.044 }, speed: { aa: 131, ls: null } },
      { name: 'Gemini 3.8 Flash High', maker: 'Google', open: false,
        scores: { aa: 41, ls: 51.3, lb: null, lm: 1610 },
        cost: { perM: 3.75, perTask: 0.58, perSuccess: null }, speed: { aa: 321, ls: null } },
    ],
  },

  {
    key: 'chat',
    label: 'Chat 对话',
    sub: '主信号只有 LMArena Text Arena（人类偏好，无可替代）。AA 智能指数做通用能力校验，LiveBench 测不到"说人话"，故不展示。',
    kicker: 'DIMENSION 02',
    lmMetric: 'Text Arena Elo（人类对话偏好）',
    cols: ['aa', 'ls', 'lm'],
    costLabel: '输出 $/M',
    speedLabel: '输出 t/s',
    note: '头部 10 名 Elo 差距不到 30 分，而 LMArena 官方口径是 25 分内属噪声——榜首之争基本是本周样本浮动。注意 GPT-6 Astra 文本榜仅第 24（~1480），却在 WebDev 榜首：同一个模型，聊天与做页面是两个构念。',
    analysis: [
      { k: '偏好 ≠ 客观', lead: 'Text Arena 测的是"用户随手问的短问题"体感，与任务榜常年背离，这不是 bug 是构念不同。',
        body: ['Claude 系包揽 Text Arena 前四：Mythos 5 1531、Fable 5.1 ~1527、Fable 5 1525、Opus 5 1522，四者分差在噪声范围内基本并列。',
               'Kimi K3 文本 1500 与闭源旗舰同处一个 Elo 带，且开着开放权重——chat 场景里最被低估的一个。',
               'GPT-6 Astra 文本榜第 24（~1480）明显落后于它的能力榜排名，说明"更聪明"不等于"更讨喜"。'],
        note: 'Chat 维度只放 LMArena 一个数 + AA 指数做背景即可，硬凑四个源反而会制造虚假精度。' },
      { k: '怎么读 Elo', lead: '9 月首次有三款模型同时越过 1510：Mythos 5 / Fable 5.1 / Fable 5，开放权重已贴到 1500 线。',
        body: ['<20 分差 = 噪声（当并列看）；20–50 分 = 小但一致的差距；>50 分 = 肉眼可辨。',
               '投票数差异可达两个数量级：低票模型置信区间宽，别把它当定论。'],
        note: '本维度 lm 列为人工快照（2026-09-15 主要盘），可在页面直接点改。' },
    ],
    models: [
      { name: 'Claude Mythos 5', maker: 'Anthropic', open: false,
        scores: { aa: null, ls: 55.4, lm: 1531 },
        cost: { perM: 50, perTask: null, perSuccess: null }, speed: { aa: null, ls: null } },
      { name: 'Claude Fable 5.1 (Max)', maker: 'Anthropic', open: false,
        scores: { aa: 53, ls: 57.0, lm: 1527 },
        cost: { perM: 50, perTask: 7.63, perSuccess: 1.439 }, speed: { aa: 35, ls: null } },
      { name: 'Claude Fable 5', maker: 'Anthropic', open: false,
        scores: { aa: 50, ls: 54.9, lm: 1525 },
        cost: { perM: 50, perTask: 3.14, perSuccess: 1.439 }, speed: { aa: 119, ls: null } },
      { name: 'Claude Opus 5 (Max)', maker: 'Anthropic', open: false,
        scores: { aa: 51, ls: 55.8, lm: 1522 },
        cost: { perM: 25, perTask: 2.34, perSuccess: null }, speed: { aa: 80, ls: null } },
      { name: 'GPT-5.6 Sol', maker: 'OpenAI', open: false,
        scores: { aa: 47, ls: 56.0, lm: 1514 },
        cost: { perM: 30, perTask: 0.95, perSuccess: 0.515 }, speed: { aa: 121, ls: null } },
      { name: 'Kimi K3 Max', maker: 'Moonshot', open: true, flag: 'Kimi K3 许可',
        scores: { aa: 44, ls: 54.1, lm: 1500 },
        cost: { perM: 15, perTask: 0.84, perSuccess: 0.348 }, speed: { aa: 86, ls: null } },
      { name: 'Muse Spark 1.3 (xhigh)', maker: 'Meta', open: false,
        scores: { aa: 48, ls: 55.4, lm: 1499 },
        cost: { perM: 4.25, perTask: 0.55, perSuccess: null }, speed: { aa: 93, ls: null } },
      { name: 'Gemini 3.8 Flash High', maker: 'Google', open: false,
        scores: { aa: 41, ls: 51.3, lm: 1493 },
        cost: { perM: 3.75, perTask: 0.58, perSuccess: null }, speed: { aa: 321, ls: null } },
      { name: 'Qwen3.8 Max', maker: 'Alibaba', open: false,
        scores: { aa: 40, ls: 52.3, lm: 1491 },
        cost: { perM: 6, perTask: null, perSuccess: null }, speed: { aa: 71, ls: null } },
      { name: 'GLM-5.3 (Max)', maker: 'Z.ai', open: true, flag: 'MIT',
        scores: { aa: 45, ls: 53.8, lm: 1487 },
        cost: { perM: 4.0, perTask: 0.09, perSuccess: 0.031 }, speed: { aa: 87, ls: null } },
      { name: 'GPT-6 Astra (Max)', maker: 'OpenAI', open: false,
        scores: { aa: 53, ls: 57.5, lm: 1480 },
        cost: { perM: 50, perTask: 3.26, perSuccess: null }, speed: { aa: 60, ls: null } },
      { name: 'DeepSeek V4 Pro 0813', maker: 'DeepSeek', open: true, flag: 'MIT',
        scores: { aa: 36, ls: 52.3, lm: 1462 },
        cost: { perM: 0.87, perTask: null, perSuccess: 0.044 }, speed: { aa: 131, ls: null } },
    ],
  },

  {
    key: 'image',
    label: '图像生成',
    sub: '主信号：AA Image Arena 与 LMArena T2I 互校。两站都用 Elo，但 AA 于 9 月重标定过刻度，跨版本不可比、只在同站内比。',
    kicker: 'DIMENSION 03',
    lmMetric: 'Text-to-Image Arena Elo',
    cols: ['aa', 'lm'],
    costLabel: '$/1k 图',
    speedLabel: '生成秒数',
    note: 'GPT Image 2.5（Flare / Sunburst，9-08 发布）在 AA 与 LMArena 双双拿下前二，把 GPT Image 2 挤到第三。开源权重最佳为 Ideogram 4.0（AA 1017）；HiDream 与 Cosmos3 已跌出 AA 前十。',
    analysis: [
      { k: '两榜同向：GPT Image 2.5 登顶', lead: 'AA 与 LMArena 在"谁是第一"上这次难得一致，GPT Image 2.5 两个变体包揽前二。',
        body: ['AA：Flare 1187 第 1、Sunburst 1180 第 2、GPT Image 2 1171 第 3；LMArena：Sunburst 1421 第 1、Flare 1399 第 2、GPT Image 2 1381 第 3。',
               '注意 AA 在 9 月重标定过 Elo 刻度（现在的 1187 ≈ 旧刻度的 1368），所以 AA 与 LMArena 的绝对值不能直接比，只能各自在本站内排序。'],
        note: '选图：先定闭源/开源，再在两站内比 Elo；需要可控性优先开源权重本地部署。' },
      { k: '开源与闭源的差距', lead: '闭源前沿（AA ~1180）与最强开源（Ideogram 4.0 ~1017）之间仍有约 160 分差距。',
        body: ['FLUX.2 [dev]（AA 1000）是本地部署最实用的选择，非商用许可；Ideogram 4.0 强在排版与文字。',
               '图像编辑榜另有一套刻度：GPT Image 2.5 Sunburst ~1167 第一，Reve 2.1 是编辑方向的强项。'],
        note: '本维度 lb/ls 无图像榜，故只显示 AA 与 LMArena 两源。' },
    ],
    models: [
      { name: 'GPT Image 2.5 Flare (Max)', maker: 'OpenAI', open: false,
        scores: { aa: 1187, lm: 1399 },
        cost: { per1k: null }, speed: { gen: 11 } },
      { name: 'GPT Image 2.5 Sunburst (Max)', maker: 'OpenAI', open: false,
        scores: { aa: 1180, lm: 1421 },
        cost: { per1k: null }, speed: { gen: 13 } },
      { name: 'GPT Image 2 (medium)', maker: 'OpenAI', open: false,
        scores: { aa: 1171, lm: 1381 },
        cost: { per1k: 211 }, speed: { gen: 12 } },
      { name: 'MAI-Image-2.6', maker: 'Microsoft AI', open: false,
        scores: { aa: 1145, lm: 1331 },
        cost: { per1k: null }, speed: { gen: 9 } },
      { name: 'Reve 2.1', maker: 'Reve', open: false,
        scores: { aa: 1127, lm: 1301 },
        cost: { per1k: null }, speed: { gen: 8 } },
      { name: 'Nano Banana 2 (Gemini 3.1 Flash Image)', maker: 'Google', open: false,
        scores: { aa: 1122, lm: 1261 },
        cost: { per1k: 67 }, speed: { gen: 4 } },
      { name: 'Muse Image', maker: 'Meta', open: false,
        scores: { aa: 1110, lm: 1277 },
        cost: { per1k: null }, speed: { gen: 10 } },
      { name: 'Grok Imagine Image 2.0', maker: 'SpaceXAI', open: false,
        scores: { aa: null, lm: 1315 },
        cost: { per1k: null }, speed: { gen: 7 } },
      { name: 'Seedream 5.0 Pro', maker: 'ByteDance', open: false,
        scores: { aa: null, lm: 1257 },
        cost: { per1k: null }, speed: { gen: 6 } },
      { name: 'Qwen-Image-3.0-Pro', maker: 'Alibaba', open: false,
        scores: { aa: null, lm: 1254 },
        cost: { per1k: null }, speed: { gen: 6 } },
      { name: 'Ideogram 4.0', maker: 'Ideogram', open: true, flag: '开放模型',
        scores: { aa: 1017, lm: 1204 },
        cost: { per1k: null }, speed: { gen: 9 } },
      { name: 'FLUX.2 [dev]', maker: 'Black Forest Labs', open: true, flag: '非商用',
        scores: { aa: 1000, lm: null },
        cost: { per1k: null }, speed: { gen: 4 } },
    ],
  },

  {
    key: 'video',
    label: '视频生成',
    sub: '主信号：AA 与 LMArena 的 Image-to-Video Arena 互校（同一子赛道，可比）。不含语音互转。Sora 已停服。',
    kicker: 'DIMENSION 04',
    lmMetric: 'I2V Arena Elo',
    cols: ['aa', 'lm'],
    costLabel: '$/秒',
    speedLabel: '—',
    note: 'Sora 应用已关停、API 于 2026-09-24 到期，勿再选型。中国实验室占据多数席位；Google 的 Gemini Omni Flash 与阿里 Wan 3.0 在两源均居前。部分模型仅 LMArena 有值，分歧带会标"缺源"，属正常。',
    analysis: [
      { k: '中国实验室主导，Google 仍有一席', lead: 'I2V 榜上 MiniMax H3、Gemini Omni Flash、Wan 3.0 三强争霸，国产模型占据前十多数。',
        body: ['LMArena I2V：MiniMax H3 1497 第 1、Gemini Omni 1.1 Flash 1488、Wan 3.0 1481；AA I2V：Gemini Omni Flash 1366 第 1、Wan 3.0 1362、MiniMax H3 1351——两源对"谁是第一"略有分歧，但都把这三者放在最前。',
               'MiniMax H3 与 Wan 3.0 均为开放权重，是当前能自托管的最强视频模型。'],
        note: '选视频：要音频/成品选 Veo 3.1（48kHz 同步对话）或 Kling 3.0；要性价比选 Seedance 2.0（$0.022/s）；要自托管选 Wan 3.0 / MiniMax H3。' },
      { k: '两个源各覆盖不同的模型', lead: 'AA 与 LMArena 的 I2V 榜单模型重叠度有限，很多模型只有一方有值。',
        body: ['有双源值的（可看分歧）：Gemini Omni Flash、Wan 3.0、MiniMax H3、Seedance 2.0、Grok Imagine Video 1.5。',
               '仅 LMArena 有值的：Seedance 2.5、HiDream O1 Video、FLUX 3 Video、Veo 3.1、Kling 3.0 Pro——分歧带会标"缺源"。'],
        note: '本维度 lm 列取 LMArena I2V；AA 列取 AA Image-to-Video Arena，两源同子赛道，可直接对照。' },
    ],
    models: [
      { name: 'MiniMax H3', maker: 'MiniMax', open: true, flag: '开放权重',
        scores: { aa: 1351, lm: 1497 },
        cost: { perSec: 0.12 } },
      { name: 'Gemini Omni Flash', maker: 'Google', open: false,
        scores: { aa: 1366, lm: 1464 },
        cost: { perSec: 0.15 } },
      { name: 'Wan 3.0', maker: 'Alibaba', open: true, flag: 'Apache 2.0',
        scores: { aa: 1362, lm: 1481 },
        cost: { perSec: 0.10 } },
      { name: 'Seedance 2.5', maker: 'ByteDance', open: false,
        scores: { aa: null, lm: 1475 },
        cost: { perSec: null } },
      { name: 'Seedance 2.0', maker: 'ByteDance', open: false,
        scores: { aa: 1344, lm: 1474 },
        cost: { perSec: 0.022 } },
      { name: 'Grok Imagine Video 1.5', maker: 'SpaceXAI', open: false,
        scores: { aa: 1331, lm: 1456 },
        cost: { perSec: 0.14 } },
      { name: 'HiDream O1 Video 1.0', maker: 'HiDream', open: true, flag: '开放权重',
        scores: { aa: null, lm: 1452 },
        cost: { perSec: null } },
      { name: 'FLUX 3 Video', maker: 'Black Forest Labs', open: false,
        scores: { aa: null, lm: 1450 },
        cost: { perSec: null } },
      { name: 'Veo 3.1', maker: 'Google', open: false,
        scores: { aa: null, lm: 1398 },
        cost: { perSec: 0.15 } },
      { name: 'Kling 3.0 Pro', maker: 'Kuaishou', open: false,
        scores: { aa: null, lm: 1355 },
        cost: { perSec: 0.10 } },
    ],
  },
];
